version: '3.7'
services:
    web:
        build: .
        image: git_cloner_app
        command: gunicorn --bind 0.0.0.0:5000 web.main:app
        ports:
            - "5000:5000"
        env_file:
            - env/credentials.env

